version: '2'

services:
  slides:
    image: hairyhenderson/remarkjs
    volumes:
      - ./slides.md:/usr/share/nginx/html/slides.md
      - ./index.html.tmpl:/index.html.tmpl
      - ./images:/usr/share/nginx/html/images
      - ./styles.css:/usr/share/nginx/html/styles.css
    environment:
      - TITLE=Docker 1.13
      - HIGHLIGHT_LINES=true
      - HIGHLIGHT_SPANS=true
      - RATIO=16:9
      - DEV_MODE=true
    ports:
      - 8080:80
